apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-issuer.yaml
- grpc-quirks.yaml
- home.yaml
- ingress.yaml
- ingress-grpc.yaml
- kaja.yaml
- teams.yaml
- twirp-quirks.yaml
- users.yaml
- workspace-volume.yaml