apiVersion: apps/v1
kind: Deployment
metadata:
  name: twirp-quirks-deployment
  labels:
    app: twirp-quirks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twirp-quirks
  template:
    metadata:
      labels:
        app: twirp-quirks
    spec:
      containers:
      - name: twirp-quirks
        image: kajatools/website-quirks:latest
        imagePullPolicy: Always
        command: ["./twirp-server"]
        ports:
        - containerPort: 41523
---
apiVersion: v1
kind: Service
metadata:
  name: twirp-quirks-service
spec:
  selector:
    app: twirp-quirks
  ports:
    - port: 80
      targetPort: 41523
  type: ClusterIP
